Drupal 10 compatibility fixes
City-of-Helsinki/drupal-module-helfi-ahjo-org-chart pull request #1
Opened 2024-03-13 14:27 UTC by juho-lehmonen

2024-10-14 09:54 UTC, hyrsky commented on .github/workflows/ci.yml
> +      - main
TODO after this is merged: change main branch to main from https://github.com/City-of-Helsinki/drupal-module-helfi-ahjo-org-chart/settings.

2024-10-14 09:55 UTC, hyrsky requested changes

2024-10-14 09:55 UTC, hyrsky commented on helfi_ahjo.module
> +  // the block configs already removed from other instances.
This comment is not relevant for this module.

2024-10-14 10:24 UTC, hyrsky requested changes

2024-10-14 10:24 UTC, hyrsky commented on helfi_ahjo.module
I think this module needs to implement `hook_helfi_paragraph_types` for `sote_section` paragraph so it can be placed.

2024-10-14 10:27 UTC, hyrsky commented on helfi_ahjo.module
> +  // the block configs already removed from other instances.
I don't think we need to add this modules config to config ignore at all, since we should set api keys in `*settings.php`.

2024-10-15 09:56 UTC, juho-lehmonen commented on helfi_ahjo.module
> +  // the block configs already removed from other instances.
This has been changed to only ignore the API key now.

2024-10-15 12:45 UTC, hyrsky approved these changes

2024-10-15 13:29 UTC, merged